name: DA
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - matplotlib=3.9.2=py311haa95532_0
  - numpy=1.26.4=py311hdab7c0b_0
  - pandas=2.2.2=py311hea22821_0
  - scipy=1.14.1=py311h9f229c6_0
  - seaborn=0.13.2=py311haa95532_0
  - streamlit=1.40.1

